# Generated by Django 4.2.16 on 2024-10-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='payment_type',
        ),
    ]
