# Generated by Django 4.2.16 on 2024-10-24 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spot_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
