# Generated by Django 4.2.16 on 2024-10-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_share', '0002_address_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='available_end',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
