# Generated by Django 4.2.16 on 2024-10-30 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_share', '0002_remove_parking_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
