# Generated by Django 4.2.16 on 2024-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_share', '0003_alter_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=10),
        ),
    ]
