# Generated by Django 4.2.16 on 2024-10-30 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spot_share', '0003_alter_lease_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lessor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_lessor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease',
            name='lessor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_tenant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_approved',
            field=models.BooleanField(default=False),
        ),
    ]
