# Generated by Django 4.2.16 on 2024-10-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_share', '0004_parking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='users',
            new_name='staff_users',
        ),
    ]
