# Generated by Django 4.2.16 on 2024-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_share', '0005_alter_lease_lessor_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='status',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='status',
        ),
        migrations.AddField(
            model_name='lease',
            name='staff_approved',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='parking',
            name='staff_approved',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
