# Generated by Django 4.2.16 on 2024-10-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot_share', '0006_remove_lease_status_remove_parking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spot_share.parking'),
        ),
    ]
